### ISSUE TITLE
nvdbswe2osm on AWS pipeline

### ISSUE THREAD

**Issue by matthiasfeist** [NKAmapper/nvdb2osm#9]
Hi @NKAmapper 

I just wanted to break out the discussion of running this script on my AWS pipline.
I wonder why you use the _homogeniserad_ format. The problem I have with this is that this format doesn't seem to be automatically downloadable from Lastkajen Logistics. Or at least I have not found it...

**Comment by atorger** [comment]
Quick comment, my script is ~5700 lines of code, NKA's script is ~1400 lines of code. The large difference is because my script uses the NVDB in raw form and need to merge layers, so the script is actually more about merging geometry than actual tag translation. So I assume the homogeniserad format is used to make the script smaller and concentrate on actual tag translation and not too much on the geometry.

If I had known in advance how complicated it would be to merge NVDB layers (due to gaps and quirks etc) I may have chosen a different route myself... but now when the code seems to work for all municipalities it's nice to have when doing batch runs...

**Comment by matthiasfeist** [comment]
Ahhh makes sense :)

**Comment by NKAmapper** [comment]
My script was just a test to have quick look at the data, mostly reusing code which I already had. The _homogeniserad_ format has the advantage that all road segments are already split at each intersection, and all road attributes are already assigned to each segment. So it is very easy to consume.

However, atorger has taken the right approach, choosing a format which contains all available data and which is readily available without an order/delivery process. The other alternative would have been XML, which contains everything, and with the added benefit of having segments which do not cross intersections (but the files also contain history and are big).

Merging layers should not be terribly difficult, though, because there is no need to use the coordinates of each layer, just the start/end metering values which are references to the relative position in the basic road network. I am using this approach in the Norwegian [nvdb2osm](https://github.com/NKAmapper/nvdb2osm), and this way I get a linear complexity with each municipality running in just a few seconds. The difficult task is snapping to the right node, which I guess is cause trouble.

By the way, Lastkajen will get a new version in a few weeks, and some old formats will be gone and new ones will be introduced.

**Comment by atorger** [comment]
In the first version I used only the metering values (STARTAVST, SLUTAVST) for merging, but the problem with those is that the data is not perfect. There's gaps here and there, the reference geometry does not always have 100% coverage and other quirks here and there. I had to add more and more special cases and in the end it was so messy that I made a new way database that understands the geometry and can compensate for more mismatches in the data and integrates with the snapping. There's plenty of alignment issues, so various type of snapping is necessary in any case.

One can most probably trust the metering more than is done in my code now though. I have deliberately tried to rely on them as little as possible, and the code is thus more capable dealing with geometry than it needs to be. Now the metering values are only used as guides to repair the most severe geometry errors, if the data would be fully correct they wouldn't be needed at all.

Had I known how complicated it would be to make the code for not depending on the metering values, I would probably have tried a bit more with the previous approach though...
